// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL0iyomO_VwM-cCnQC48K53lWayI3AE3g',
    appId: '1:776327766923:web:f8f146ed30396188c7458e',
    messagingSenderId: '776327766923',
    projectId: 'kanbagis-9b3e9',
    authDomain: 'kanbagis-9b3e9.firebaseapp.com',
    storageBucket: 'kanbagis-9b3e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHWWEQ-qeheNorP-MvnQclP-DflR8P7ns',
    appId: '1:776327766923:android:4a8a2cc645464995c7458e',
    messagingSenderId: '776327766923',
    projectId: 'kanbagis-9b3e9',
    storageBucket: 'kanbagis-9b3e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH2w_ST6WtUxO_NRavgTHKSURFPs2qqRo',
    appId: '1:776327766923:ios:b14985ac85b3bddcc7458e',
    messagingSenderId: '776327766923',
    projectId: 'kanbagis-9b3e9',
    storageBucket: 'kanbagis-9b3e9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH2w_ST6WtUxO_NRavgTHKSURFPs2qqRo',
    appId: '1:776327766923:ios:b14985ac85b3bddcc7458e',
    messagingSenderId: '776327766923',
    projectId: 'kanbagis-9b3e9',
    storageBucket: 'kanbagis-9b3e9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL0iyomO_VwM-cCnQC48K53lWayI3AE3g',
    appId: '1:776327766923:web:5f41fa962522131fc7458e',
    messagingSenderId: '776327766923',
    projectId: 'kanbagis-9b3e9',
    authDomain: 'kanbagis-9b3e9.firebaseapp.com',
    storageBucket: 'kanbagis-9b3e9.firebasestorage.app',
  );
}
